name       : python-gssapi
version    : 1.8.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/g/gssapi/gssapi-1.8.1.tar.gz : 893aa38ae769d1febe89963aa9f59194a966736ade2263fe14e0081126d64a72
homepage   : https://github.com/pythongssapi/python-gssapi
license    : ISC
component  : programming.python
summary    : Python GSSAPI Wrapper
description: |
    Python-GSSAPI provides both low-level and high level wrappers around the GSSAPI C libraries. While it focuses on the Kerberos mechanism, it should also be useable with other GSSAPI mechanisms.
builddeps  :
    - pkgconfig(krb5)
    - cython
rundeps    :
    - python-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
