name       : python-gssapi
version    : 1.8.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/g/gssapi/gssapi-1.8.2.tar.gz : b78e0a021cc91158660e4c5cc9263e07c719346c35a9c0f66725e914b235c89a
homepage   : https://github.com/pythongssapi/python-gssapi
license    : ISC
component  : programming.python
summary    : Python GSSAPI Wrapper
description: |
    Python-GSSAPI provides both low-level and high level wrappers around the GSSAPI C libraries. While it focuses on the Kerberos mechanism, it should also be useable with other GSSAPI mechanisms.
builddeps  :
    - pkgconfig(krb5)
    - cython
rundeps    :
    - python-decorator
build      : |
    %python3_setup
install    : |
    %python3_install
